## YAML Template.

sf_grid_jsontest:
    pattern:  dev/grid/test
    defaults: { _controller: "GridLBundle:gridObj:jsontest" }
sf_grid_jstest:
    pattern:  dev/gridjs/test
    defaults: { _controller: "GridLBundle:gridObj:jstest" }
sf_grid_servicetest:
    pattern:  dev/gridservice/test
    defaults: { _controller: "GridLBundle:gridObj:servicetest" }
sf_grid_load:
    pattern:  dev/gridservice/load
    defaults: { _controller: "GridLBundle:gridObj:load" }

grid_crud:
    resource: "@GridLBundle/Resources/config/entity/routing.yml"
    prefix:   /