## YAML Template.
---
parameters:
    grid.entity_wrapper.class: Lamari\GridLbundle\Tools\GridEntity
    grid.extension.class: Lamari\GridLbundle\Twig\GridLExtension

services:
    grid.entity_wrapper:
        class: Lamari\GridLBundle\Tools\GridEntity
        arguments: ["@doctrine.orm.entity_manager","@router","@request","@templating"]
    grid.extension:
        class: Lamari\GridLBundle\Twig\GridLExtension
        arguments: ["@templating"]
        tags: 
            - { name: twig.extension }
